# 工作流的名称
name: hugo-deploy

# 触发事件
on:
  # 当你向主分支 main 推送了代码时触发此工作流
  push:
    paths-ignore:
      - "images/**"
      - "LICENSE"
      - "README.md"
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          ref: main
          submodules: true
          fetch_depth: 1

      #- name: Get Theme
      #run: git submodule update --init --recursive

      #- name: Update theme to Latest commit
      #run: git submodule update --remote --merge

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.83.0"

      - name: Build
        run: hugo --buildDrafts --gc --verbose --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      #这里是开始同步仓库库到gitee
      - name: Mirror the Github organization repos to Gitee.
        #uses: Yikun/hub-mirror-action@v1.2
        uses: Yikun/hub-mirror-action@master
        with:
          src: "github/moxiaobei1993"
          dst: "gitee/moxiaobei1993"
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          mappings: "moxiaobei1993.github.io=>blog"
          white_list: "moxiaobei1993.github.io"
          static_list: "moxiaobei1993.github.io"
          force_update: true
          debug: true
